
moment = require 'moment'

module.exports = (grunt) ->
  target = grunt.option('e') || 'dev'

  grunt.initConfig

    coffee:
      srv:
        expand: true
        cwd: 'src/'
        src: ['*.coffee', '**/*.coffee']
        dest: 'app/'
        ext: '.js'
      client:
        expand: true
        cwd: 'assets/elements'
        src: ['*/*.coffee']
        dest: 'assets/elements/'
        ext: '.js'
      deps:
        expand: true
        src: ['utils/*.coffee', 'models/*.coffee', 'services/*.coffee']
        dest: 'app/'
        ext: '.js'
    coffeelint:
      options:
        max_line_length: { level: 'ignore' }
        eol_last: { level: 'warn' }
      srv: ['src/**/*.coffee']
      client: ['assets/elements/*/*.coffee']
      deps: ['utils/**/*.coffee', 'models/*.coffee', 'services/*.coffee']
    # concat:
    #   less:
    #     src: ['assets/less/default/app.less', 'assets/less/default/**/*.less']
    #     dest: 'assets/less/clients/default.less'
    #     options: { banner: "// This file is automatically generated from the files in assets/less/default.\n// Do not edit manually\n" }
    # less:
    #   main:
    #     expand: true
    #     src: ['assets/less/clients/**/*.less']
    #     dest: 'assets/css/'
    #     flatten: true
    #     ext: '.css'
      # css:
      #   expand: true
      #   src: 'assets/css/*.css'
      #   ext: '.min.css'
    exec:
      debug:
        cmd: 'node-debug ./app/app.js'
    concurrent:
      dev:
        tasks: ['watch', 'nodemon']
        options:
          logConcurrentOutput: true
    nodemon:
      dev:
        script: 'app/app.js'
        options:
          watch: ['app/**/*.js', 'config/']
          ext: 'js,yml'
          delay: 1000
          # nodeArgs: '--use-strict' # fails some dependencies (bunyan)
    watch:
      srv:
        files: ['src/*.coffee', 'src/**/*.coffee']
        tasks: ['coffeelint:srv', 'clean:srv', 'coffee:srv']
      deps:
        files: ['models/*.coffee', 'utils/*.coffee', 'services/*.coffee']
        tasks: ['coffeelint:deps', 'clean:deps', 'coffee:deps']
      client:
        files: ['assets/elements/*/*.coffee']
        tasks: ['coffeelint:client', 'coffee:client']
    clean:
      options: {force: true}
      srv: ['app/*.js', 'app/controllers/**']
      deps: ['app/models/**', 'app/utils/**', 'app/services/**']
    chequire:
      all: ['app/**/*.js']


  # grunt.loadTasks('grunt_tasks')
  grunt.loadNpmTasks 'grunt-contrib-clean'
  grunt.loadNpmTasks 'grunt-contrib-coffee'
  # grunt.loadNpmTasks 'grunt-contrib-concat'
  # grunt.loadNpmTasks 'grunt-contrib-cssmin'
  # grunt.loadNpmTasks 'grunt-contrib-less'
  # grunt.loadNpmTasks 'grunt-contrib-uglify'
  grunt.loadNpmTasks 'grunt-contrib-watch'
  grunt.loadNpmTasks 'grunt-chequire'
  grunt.loadNpmTasks 'grunt-coffeelint'
  grunt.loadNpmTasks 'grunt-concurrent'
  grunt.loadNpmTasks 'grunt-exec'
  grunt.loadNpmTasks 'grunt-nodemon'
  # grunt.loadNpmTasks 'grunt-regex-replace'

  # group sub-tasks into bigger chunks

  grunt.registerTask 'base', ['coffeelint', 'clean', 'coffee']
  grunt.registerTask 'default', ['base', 'concurrent']
  grunt.registerTask 'debug', ['base', 'exec:debug']
