server:
  port: 3001
  cluster: false

db: mongodb://rasteau:27017/vinisync

session: # redis session details
  host: rasteau
  port: 7396
  duration: 3600 # session duration, in seconds
  appName: 'vinisync'

log:
  level: debug
  output:
    -
      target: trace.log
