
dbConnections:
  - connectionString: mongodb://localhost:27017/vinisync
    name: vni

server:
  port: 3001
  cluster: false

session: # redis session details
  host: localhost:7396
  duration: 604800 # session duration, in seconds
  appName: 'vinisync'

log:
  level: debug
  targets:
    -
      type: stdout
    -
      type: file
      path: trace.log

imageDirectory: /home/bleuarff/dev/vni_uploads
